### ISSUE TITLE
Style Products

### ISSUE THREAD

**Issue by TNortnern** [fnicoletta/cow-milk#6]
Style the Products page and components.

- Page /pages/Products

- Add to Cart - should trigger a modal asking for quantity and size, wireframe: COMING SOON

- See Product - should route to a new page of a single product view - wireframe: COMING SOON

- On Page Click - should bring user to the top of products

- ProductsList - needs to have a min-height or set height so that the layout doesn't randomly change if there isn't 8 products

**Comment by ebebbington** [comment]
It seems points 1 & 2 have already been developed. Is somebody already working on this?
